services:
  - type: static_site
    name: avira-health-centre
    env: static
    buildCommand: ""         # leave blank if no build needed
    publishDir: .            # root folder containing index.html
    domains:
      - avirahealthcentre.in      # optional custom domain
