services:
  - type: web
    name: avira-health-centre
    env: static
    buildCommand: ""       # leave blank if no build is needed
    publishDir: .          # folder where index.html is located
    domains:
      - avirahealthcentre.in
