name: 🚀 Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🔐 SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            rm -rf /var/www/html/*
            git clone https://github.com/sarthak-13N/avirahealthcentre.git temp
            cp -r temp/* /var/www/html/
            rm -rf temp
